import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const cfg=window.GESTION_BTP_SUPABASE||{};
if(/^https:\/\/.+\.supabase\.co$/.test(cfg.url||"")&&String(cfg.anonKey||"").length>30){
  const db=createClient(cfg.url,cfg.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  const ROLES={admin:"Administrateur technique",patron:"Patron",direction:"Direction",conducteur:"Conducteur de travaux",salarie:"Salarié"};
  const ORDER=["admin","patron","direction","conducteur","salarie"];
  const PREVIEW_KEY="gestion_btp_v107_preview_role";
  let profile=null;
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const primary=p=>{const r=Array.isArray(p?.business_roles)&&p.business_roles.length?p.business_roles:[p?.business_role].filter(Boolean);for(const id of ORDER)if(r.includes(id))return id;if(p?.role==="admin")return"admin";if(p?.role==="conducteur")return"conducteur";if(p?.role==="salarie")return"salarie";return"direction"};
  const legacy=id=>id==="admin"?"admin":id==="conducteur"?"conducteur":id==="salarie"?"salarie":"rh";
  async function load(){const{data:{session}}=await db.auth.getSession();if(!session?.user)return false;const{data,error}=await db.from("profiles").select("id,email,role,status,business_role,business_roles").eq("id",session.user.id).maybeSingle();if(error||!data)return false;profile=data;return true}
  function selectedPreview(){const v=localStorage.getItem(PREVIEW_KEY);return ROLES[v]?v:primary(profile)}
  function installPreview(){const old=document.querySelector("#v66RolePreview");if(!old||!profile)return;const wrap=old.closest("label")||old.parentElement;if(!wrap)return;old.style.display="none";let select=wrap.querySelector("#v107RolePreview");if(!select){select=document.createElement("select");select.id="v107RolePreview";wrap.appendChild(select);select.addEventListener("change",()=>{const chosen=select.value,real=primary(profile);if(chosen===real)localStorage.removeItem(PREVIEW_KEY);else localStorage.setItem(PREVIEW_KEY,chosen);const lv=legacy(chosen);if(old.value!==lv){old.value=lv;old.dispatchEvent(new Event("change",{bubbles:true}))}else{location.hash="#home";location.reload()}})}select.innerHTML=ORDER.map(id=>`<option value="${id}" ${selectedPreview()===id?"selected":""}>${ROLES[id]}</option>`).join("");const shown=selectedPreview(),real=primary(profile);const label=document.querySelector(".v66-user span");if(label)label.textContent=`${ROLES[shown]}${shown!==real?" · simulation":""}`;let banner=document.querySelector(".v66-preview-banner");if(shown!==real&&banner)banner.textContent=`Mode aperçu : affichage simulé en ${ROLES[shown]}. Votre véritable compte reste ${ROLES[real]}.`}
  async function targetFromDrawer(drawer){const email=drawer.querySelector("header small")?.textContent.trim();if(!email)return null;const{data}=await db.from("profiles").select("id,email,role,business_role,business_roles").eq("email",email).maybeSingle();return data}
  function currentRoles(p){if(Array.isArray(p?.business_roles)&&p.business_roles.length)return p.business_roles.filter(x=>ROLES[x]);if(p?.business_role&&ROLES[p.business_role])return[p.business_role];return[primary(p)]}
  async function enhanceDrawer(drawer){if(drawer.dataset.v107Roles)return;drawer.dataset.v107Roles="loading";const target=await targetFromDrawer(drawer);if(!target){drawer.dataset.v107Roles="error";return}const section=[...drawer.querySelectorAll("section")].find(s=>s.querySelector('input[name="role"]'));if(!section){drawer.dataset.v107Roles="error";return}const old=section.querySelector(".v66-choice-list");if(old)old.style.display="none";const targetRoles=currentRoles(target),meRoles=currentRoles(profile),isAdmin=meRoles.includes("admin"),isPatron=meRoles.includes("patron");if(!isAdmin&&!isPatron){const p=document.createElement("p");p.className="v66-help";p.innerHTML=`Rôles : <strong>${targetRoles.map(r=>esc(ROLES[r])).join(" + ")}</strong>`;section.appendChild(p);drawer.dataset.v107Roles="readonly";return}const allowed=isAdmin?ORDER:["direction","conducteur","salarie"];const box=document.createElement("div");box.className="v66-choice-list v107-role-list";box.innerHTML=allowed.map(id=>`<label class="v66-choice-tile"><input type="checkbox" name="business_roles_v107" value="${id}" ${targetRoles.includes(id)?"checked":""}><span><b>${ROLES[id]}</b><i aria-hidden="true"></i></span></label>`).join("");section.appendChild(box);const note=document.createElement("p");note.className="v66-help";note.textContent="Plusieurs rôles peuvent être cochés pour une même personne, par exemple Patron + Conducteur de travaux.";section.appendChild(note);const submit=drawer.querySelector('footer button[type="submit"],footer button:not([type]),button.v66-btn.primary');if(submit&&!submit.dataset.v107Intercept){submit.dataset.v107Intercept="1";submit.addEventListener("click",async e=>{if(drawer.dataset.v107Bypass==="1"){drawer.dataset.v107Bypass="0";return}e.preventDefault();e.stopImmediatePropagation();const roles=[...drawer.querySelectorAll('input[name="business_roles_v107"]:checked')].map(x=>x.value);const msg=drawer.querySelector(".v66-message");if(!roles.length){if(msg){msg.textContent="Choisissez au moins un rôle.";msg.className="v66-message error"}return}submit.disabled=true;try{const{error}=await db.rpc("set_business_roles_v2",{target_id:target.id,new_roles:roles});if(error)throw error;const p=ORDER.find(x=>roles.includes(x))||"salarie",lv=legacy(p),radio=drawer.querySelector(`input[name="role"][value="${lv}"]`);if(radio)radio.checked=true;drawer.dataset.v107Bypass="1";submit.disabled=false;submit.click()}catch(err){submit.disabled=false;if(msg){msg.textContent=err.message;msg.className="v66-message error"}else alert(err.message)}},true)}drawer.dataset.v107Roles="1"}
  async function enhance(){if(!profile&&!(await load()))return;installPreview();document.querySelectorAll(".v66-account-drawer").forEach(d=>enhanceDrawer(d).catch(console.warn))}
  const ob=new MutationObserver(()=>{clearTimeout(ob.t);ob.t=setTimeout(enhance,80)});ob.observe(document.documentElement,{subtree:true,childList:true});setTimeout(enhance,300);
}
