import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { V2_ROLE_LABELS, v2Role } from "./v2-role-config.js";
const cfg=window.GESTION_BTP_SUPABASE||{};
if(/^https:\/\/.+\.supabase\.co$/.test(cfg.url||"")&&String(cfg.anonKey||"").length>30){
  const db=createClient(cfg.url,cfg.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  let checked=false;
  function inject(){if(document.getElementById("v2StatusStyle"))return;const s=document.createElement("style");s.id="v2StatusStyle";s.textContent=`.v2-status{display:flex;align-items:center;gap:8px;padding:8px 12px;border-radius:999px;font-size:12px;font-weight:900}.v2-status.ok{background:#e4f4ea;color:#08643f}.v2-status.warn{background:#fff5dc;color:#755300}.v2-status-dot{width:8px;height:8px;border-radius:50%;background:currentColor}.v2-setup-banner{margin:12px auto 0;max-width:1100px;padding:11px 15px;border:1px solid #eed697;border-radius:14px;background:#fff8e5;color:#6c4f00;font-weight:700}`;document.head.appendChild(s)}
  async function run(){if(checked)return;const top=document.querySelector(".v66-top-actions");if(!top)return;inject();const{data:{session}}=await db.auth.getSession();if(!session?.user)return;const{data:profile}=await db.from("profiles").select("id,role,business_role,status").eq("id",session.user.id).maybeSingle();if(!profile)return;const role=v2Role(profile);const{error}=await db.from("v2_project_time_entries").select("project_id").limit(1);let badge=top.querySelector(".v2-status");if(!badge){badge=document.createElement("span");badge.className="v2-status";top.prepend(badge)}if(error){badge.className="v2-status warn";badge.innerHTML='<span class="v2-status-dot"></span>Migration V2 à vérifier';return}badge.className="v2-status ok";badge.innerHTML='<span class="v2-status-dot"></span>V2 prête';if(role!=="admin"&&!document.querySelector(".v2-setup-banner")){const banner=document.createElement("div");banner.className="v2-setup-banner";banner.textContent=`Base V2 active. Ton rôle réel est ${V2_ROLE_LABELS[role]}. Pour administrer les rôles et tester toutes les fonctions, ton compte devra être défini une fois en Administrateur technique.`;document.querySelector(".v66-top")?.after(banner)}checked=true}
  const ob=new MutationObserver(()=>setTimeout(run,80));ob.observe(document.documentElement,{subtree:true,childList:true});setTimeout(run,400)
}
